TestingPJ/Models/Khachhang.cs
using System;
using System.Collections.Generic;

namespace TestingPJ.Models
{
    public partial class Khachhang
    {
        public Khachhang()
        {
            MaDatPhongs = new HashSet<Booking>();
        }

        public string MaKhachHang { get; set; } = null!;
        public string Ho { get; set; } = null!;
        public string? Dem { get; set; }
        public string Ten { get; set; } = null!;
        public DateTime NgaySinh { get; set; }
        public string Cccd { get; set; } = null!;
        public bool GioiTinh { get; set; }
        public int PhanLoai { get; set; }
        public string Sdt { get; set; } = null!;
        public string? Email { get; set; }

        public virtual ICollection<Booking> MaDatPhongs { get; set; }
    }
}

TestingPJ/Controllers/KhachhangsController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestingPJ.Models;

namespace TestingPJ.Controllers
{
    public class KhachhangsController : Controller
    {
        private readonly Quan_ly_buong_phongContext _context;

        public KhachhangsController(Quan_ly_buong_phongContext context)
        {
            _context = context;
        }

        // GET: Khachhangs
        //public async Task<IActionResult> Index()
        //{
        //      return _context.Khachhangs != null ? 
        //                  View(await _context.Khachhangs.ToListAsync()) :
        //                  Problem("Entity set 'Quan_ly_buong_phongContext.Khachhangs'  is null.");
        //}
        public IActionResult Index(int page = 1, int pageSize = 5)
        {
            var khachhangs = _context.Khachhangs.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            return View(khachhangs);
        }


        // GET: Khachhangs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Khachhangs == null)
            {
                return NotFound();
            }

            var khachhang = await _context.Khachhangs
                .FirstOrDefaultAsync(m => m.MaKhachHang == id);
            if (khachhang == null)
            {
                return NotFound();
            }

            return View(khachhang);
        }

        // GET: Khachhangs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Khachhangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaKhachHang,Ho,Dem,Ten,NgaySinh,Cccd,GioiTinh,PhanLoai,Sdt,Email")] Khachhang khachhang)
        {
            if (ModelState.IsValid)
            {
                _context.Add(khachhang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(khachhang);
        }

        // GET: Khachhangs/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Khachhangs == null)
            {
                return NotFound();
            }

            var khachhang = await _context.Khachhangs.FindAsync(id);
            if (khachhang == null)
            {
                return NotFound();
            }
            return View(khachhang);
        }

        // POST: Khachhangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MaKhachHang,Ho,Dem,Ten,NgaySinh,Cccd,GioiTinh,PhanLoai,Sdt,Email")] Khachhang khachhang)
        {
            if (id != khachhang.MaKhachHang)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(khachhang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KhachhangExists(khachhang.MaKhachHang))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(khachhang);
        }

        // GET: Khachhangs/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Khachhangs == null)
            {
                return NotFound();
            }

            var khachhang = await _context.Khachhangs
                .FirstOrDefaultAsync(m => m.MaKhachHang == id);
            if (khachhang == null)
            {
                return NotFound();
            }

            return View(khachhang);
        }

        // POST: Khachhangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Khachhangs == null)
            {
                return Problem("Entity set 'Quan_ly_buong_phongContext.Khachhangs'  is null.");
            }
            var khachhang = await _context.Khachhangs.FindAsync(id);
            if (khachhang != null)
            {
                _context.Khachhangs.Remove(khachhang);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KhachhangExists(string id)
        {
          return (_context.Khachhangs?.Any(e => e.MaKhachHang == id)).GetValueOrDefault();
        }
        public IActionResult SearchCustomers()
        {
            return View();
        }

        [HttpGet("Khachhangs/search-customer")]
        public IActionResult SearchCustomer(string maKhachHang, string sdt)
        {
            var query = _context.Khachhangs.AsQueryable();

            if (!string.IsNullOrEmpty(maKhachHang))
            {
                query = query.Where(k => k.MaKhachHang.Contains(maKhachHang));
            }

            if (!string.IsNullOrEmpty(sdt))
            {
                query = query.Where(k => k.Sdt.Contains(sdt));
            }

            var results = query.ToList();

            return Ok(results);
        }

        public IActionResult loadkhachhangs(int page = 1, int pagesize = 5)
        {
            var khachhangs = _context.Khachhangs.Skip((page - 1) * pagesize).Take(pagesize).ToList();
            return PartialView("_khachhanglist", khachhangs);
        }

        //[HttpGet]
        //public IActionResult LoadKhachhangs(int page = 1, int pageSize = 5)
        //{
        //    var khachhangs = _context.Khachhangs.Skip((page - 1) * pageSize).Take(pageSize).ToList();
        //    var data = khachhangs.Skip((page - 1) * pageSize).Take(pageSize).ToList();
        //    return PartialView("_khachhanglist", data);
        //}

        [HttpGet]
        public IActionResult GetKhachhangList(int page = 1, string maKhach = "", string cccd = "", int? phanLoai = null)
        {
            int pageSize = 5;
            var query = _context.Khachhangs.AsQueryable();

            if (!string.IsNullOrEmpty(maKhach))
            {
                query = query.Where(k => k.MaKhachHang.Contains(maKhach));
            }
            if (!string.IsNullOrEmpty(cccd))
            {
                query = query.Where(k => k.Cccd.Contains(cccd));
            }
            if (phanLoai.HasValue)
            {
                query = query.Where(k => k.PhanLoai == phanLoai.Value);
            }

            var khachhangs = query.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            return PartialView("_KhachhangList", khachhangs);
        }


    }
}

TestingPJ/Views/Khachhangs/Create.cshtml
@model TestingPJ.Models.Khachhang

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Khachhang</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaKhachHang" class="control-label"></label>
                <input asp-for="MaKhachHang" class="form-control" />
                <span asp-validation-for="MaKhachHang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ho" class="control-label"></label>
                <input asp-for="Ho" class="form-control" />
                <span asp-validation-for="Ho" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dem" class="control-label"></label>
                <input asp-for="Dem" class="form-control" />
                <span asp-validation-for="Dem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgaySinh" class="control-label"></label>
                <input asp-for="NgaySinh" class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cccd" class="control-label"></label>
                <input asp-for="Cccd" class="form-control" />
                <span asp-validation-for="Cccd" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="GioiTinh" /> @Html.DisplayNameFor(model => model.GioiTinh)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="PhanLoai" class="control-label"></label>
                <input asp-for="PhanLoai" class="form-control" />
                <span asp-validation-for="PhanLoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sdt" class="control-label"></label>
                <input asp-for="Sdt" class="form-control" />
                <span asp-validation-for="Sdt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestingPJ/Views/Khachhangs/Delete.cshtml
@model TestingPJ.Models.Khachhang

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Khachhang</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ho)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ho)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cccd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cccd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhanLoai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhanLoai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sdt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sdt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaKhachHang" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TestingPJ/Views/Khachhangs/Details.cshtml
@model TestingPJ.Models.Khachhang

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Khachhang</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ho)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ho)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cccd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cccd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhanLoai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhanLoai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sdt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sdt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MaKhachHang">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TestingPJ/Views/Khachhangs/Edit.cshtml
@model TestingPJ.Models.Khachhang

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Khachhang</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaKhachHang" />
            <div class="form-group">
                <label asp-for="Ho" class="control-label"></label>
                <input asp-for="Ho" class="form-control" />
                <span asp-validation-for="Ho" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dem" class="control-label"></label>
                <input asp-for="Dem" class="form-control" />
                <span asp-validation-for="Dem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgaySinh" class="control-label"></label>
                <input asp-for="NgaySinh" class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cccd" class="control-label"></label>
                <input asp-for="Cccd" class="form-control" />
                <span asp-validation-for="Cccd" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="GioiTinh" /> @Html.DisplayNameFor(model => model.GioiTinh)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="PhanLoai" class="control-label"></label>
                <input asp-for="PhanLoai" class="form-control" />
                <span asp-validation-for="PhanLoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sdt" class="control-label"></label>
                <input asp-for="Sdt" class="form-control" />
                <span asp-validation-for="Sdt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestingPJ/Views/Khachhangs/Index.cshtml
@model IEnumerable<TestingPJ.Models.Khachhang>

@{
    ViewData["Title"] = "Index";
}

<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<h1>Index</h1>

<div>
    <a href="@Url.Action("SearchCustomers", "KhachHangs")" class="btn btn-primary">Tìm kiếm khách</a>
    <button id="toggleSearch">Tìm kiếm khách</button>
    <div id="searchForm" style="display:none;">
        <input type="text" id="maKhach" placeholder="Mã Khách">
        <input type="text" id="cccd" placeholder="CCCD">
        <input type="text" id="phanLoai" placeholder="Phân Loại">
        <button id="searchButton">Tìm kiếm</button>
    </div>
</div>

<p>
    <a asp-action="Create">Create New</a>
</p>

<div id="khachhangListContainer">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Ho)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dem)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ten)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NgaySinh)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cccd)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GioiTinh)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PhanLoai)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sdt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ho)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dem)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ten)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NgaySinh)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cccd)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GioiTinh)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhanLoai)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sdt)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.MaKhachHang">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.MaKhachHang">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.MaKhachHang">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>




@* 
<div id="paginationContainer">
    <button onclick="loadKhachhangs(1)">First</button>
    <button onclick="loadKhachhangs(currentPage - 1)">Previous</button>
    <button onclick="loadKhachhangs(currentPage + 1)">Next</button>
    <button onclick="loadKhachhangs(totalPages)">Last</button>
</div> *@
@* <div id="paginationContainer">
    
</div> *@
<div id="paginationContainer">
    <button id="prevPage">Previous</button>
    <span id="currentPage">1</span>
    <button id="nextPage">Next</button>

</div>

<script>
    let currentPage = 1; // Initialize current page

    $(document).ready(function () {
            // Update loadKhachhangList function
        function loadKhachhangList(pageNumber, maKhach = '', cccd = '',phanLoai = null) {
            $.ajax({
                url: '@Url.Action("GetKhachhangList", "Khachhangs")',
                data: { page: pageNumber, maKhach: maKhach, cccd: cccd,phanLoai:phanLoai  },
                type: 'GET',
                success: function (response) {
                    $('#khachhangListContainer').html(response);
                    $('#currentPage').text(pageNumber);
                    currentPage = pageNumber;
                }
            });
        }
        $('#toggleSearch').click(function () {
            $('#searchForm').toggle();
        });

        // Search function
        $('#searchButton').click(function () {
            const maKhach = $('#maKhach').val();
            const cccd = $('#cccd').val();
            const phanLoai = $('#phanLoai').val();
            loadKhachhangList(currentPage, maKhach, cccd, phanLoai);
        });

        // Attach click event listeners
        $('#prevPage').click(function () {
            if (currentPage - 1 > 0) {
                loadKhachhangList(currentPage - 1);
            }
        });

        $('#nextPage').click(function () {
            loadKhachhangList(currentPage + 1);
        });

        loadKhachhangList(currentPage);  // Load the first page initially

        
    });
    // let currentPage = 1;
    // const totalPages = 2;
    // function updatePagination() {
    //     // Disable "First" and "Previous" buttons if on the first page
    //     if (currentPage === 1) {
    //         $("button[onclick='loadKhachhangs(1)']").prop("disabled", true);
    //         $("button[onclick='loadKhachhangs(currentPage - 1)']").prop("disabled", true);
    //     } else {
    //         $("button[onclick='loadKhachhangs(1)']").prop("disabled", false);
    //         $("button[onclick='loadKhachhangs(currentPage - 1)']").prop("disabled", false);
    //     }

    //     // Disable "Next" and "Last" buttons if on the last page
    //     if (currentPage === totalPages) {
    //         $("button[onclick='loadKhachhangs(currentPage + 1)']").prop("disabled", true);
    //         $("button[onclick='loadKhachhangs(totalPages)']").prop("disabled", true);
    //     } else {
    //         $("button[onclick='loadKhachhangs(currentPage + 1)']").prop("disabled", false);
    //         $("button[onclick='loadKhachhangs(totalPages)']").prop("disabled", false);
    //     }
    // }


    // $(document).ready(function () {
    //     loadKhachhangs(currentPage);
    //     updatePagination();
    // });

    // function loadKhachhangs(pageNumber) {
    //     $.ajax({
    //         url: '@Url.Action("LoadKhachhangs", "Khachhangs")',
    //         data: { page: pageNumber },
    //         type: 'GET',
    //         success: function (data) {
    //             $('#khachhangListContainer').html(data);
    //             currentPage = pageNumber;  // Update current page
    //             updatePagination();  // Update pagination buttons
    //         }   
    //     });
    // }

    // let currentPage = 1;
    // let totalPages = 0;

    // function loadKhachhangs(pageNumber) {
    //     $.ajax({
    //         url: '@Url.Action("LoadKhachhangs", "Khachhangs")',
    //         data: { pageNumber: pageNumber },
    //         type: 'GET',
    //         success: function (data) {
    //             $('#khachhangListContainer').html(data);
    //             // currentPage = pageNumber;
    //             updatePagination();  // Cập nhật nút phân trang
    //         }
    //     });
    // }
    
    // function updatePagination(totalPages, currentPage) {
    //     let buttons = '';
    //     for (let i = 1; i <= totalPages; i++) {
    //         buttons += `<button onclick="loadKhachhangs(${i})">${i}</button>`;
    //     }
    //     $('#paginationContainer').html(buttons);
    // }

    // $(document).ready(function () {
    //     loadKhachhangs(1);
    // });

</script>

TestingPJ/Views/Khachhangs/SearchCustomers.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Available Rooms</title>
    <script src="/js/Search.js"></script>
</head>
<body>
    <label for="maKhachHang">Customer ID:</label>
    <input type="text" id="maKhachHang">

    <label for="sdt">Phone Number:</label>
    <input type="text" id="sdt">

    <button onclick="searchCustomer()">Search</button>

    <div id="customerslist">
        <!-- Results will be displayed here -->
    </div>
</body>

TestingPJ/Views/Khachhangs/_KhachhangList.cshtml
@model IEnumerable<TestingPJ.Models.Khachhang>

@{
    ViewData["Title"] = "Index";
}
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ho)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ten)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgaySinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cccd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GioiTinh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhanLoai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sdt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ho)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dem)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ten)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgaySinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cccd)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GioiTinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhanLoai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sdt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.MaKhachHang">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.MaKhachHang">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.MaKhachHang">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>